import { Contract } from './types';

export const initialContracts: Contract[] = [
  {
    id: 'CONTR-2026-001',
    name: 'Salesforce Sales Cloud Pro',
    provider: 'Salesforce Inc.',
    category: 'SaaS',
    startDate: '2025-01-15',
    endDate: '2026-06-15',
    status: 'Próximo do Vencimento',
    monthlyValue: 12500,
    annualValue: 150000,
    currency: 'BRL',
    licensedSeats: 120,
    activeSeats: 85,
    excessLicenseCost: 150,
    sponsor: 'Aline Souza (Sales VP)',
    criticality: 'Alta',
    contractLink: 'https://exemplo-infra.com/contracts/salesforce_signed_2025.pdf',
    sponsorEmail: 'aline.souza@empresa.com.br',
    adminPanelLink: 'https://login.salesforce.com',
    negotiationNotes: 'Contrato renegociado em 2025 com desconto de 15%. Necessário remover as 35 licenças ociosas antes da renovação automática em junho.',
    historicCosts: [
      { month: 'Jan', value: 12500 },
      { month: 'Fev', value: 12500 },
      { month: 'Mar', value: 12500 },
      { month: 'Abr', value: 12500 },
      { month: 'Mai', value: 12500 }
    ],
    projectionRenewal: 8,
    paymentFrequency: 'Mensal',
    paymentMethod: 'Faturamento',
    installments: [
      { id: 'PARC-01', dueDate: '2026-03-15', value: 12500, status: 'Paga' },
      { id: 'PARC-02', dueDate: '2026-04-15', value: 12500, status: 'Paga' },
      { id: 'PARC-03', dueDate: '2026-05-15', value: 12500, status: 'Paga' },
      { id: 'PARC-04', dueDate: '2026-06-15', value: 12500, status: 'Próxima ao Vencimento' }
    ]
  },
  {
    id: 'CONTR-2026-002',
    name: 'Amazon Web Services (AWS)',
    provider: 'AWS Cloud Brazil',
    category: 'Infra',
    startDate: '2025-06-01',
    endDate: '2027-06-01',
    status: 'Ativo',
    monthlyValue: 48000,
    annualValue: 576000,
    currency: 'BRL',
    licensedSeats: 1,
    activeSeats: 1,
    excessLicenseCost: 0,
    sponsor: 'Tiago Mendes (CTO)',
    criticality: 'Crítica',
    contractLink: 'https://exemplo-infra.com/contracts/aws_agreement_enterprise.pdf',
    sponsorEmail: 'tiago.mendes@empresa.com.br',
    adminPanelLink: 'https://console.aws.amazon.com',
    negotiationNotes: 'Desconto de volume de dados reservada aplicado para instâncias EC2 e RDS. Avaliar desligamento de ambientes de homologação nos fins de semana.',
    historicCosts: [
      { month: 'Jan', value: 46200 },
      { month: 'Fev', value: 47100 },
      { month: 'Mar', value: 45805 },
      { month: 'Abr', value: 47900 },
      { month: 'Mai', value: 48000 }
    ],
    projectionRenewal: 5,
    paymentFrequency: 'Mensal',
    paymentMethod: 'Faturamento',
    installments: [
      { id: 'PARC-01', dueDate: '2026-04-01', value: 48000, status: 'Paga' },
      { id: 'PARC-02', dueDate: '2026-05-01', value: 48000, status: 'Paga' },
      { id: 'PARC-03', dueDate: '2026-06-01', value: 48000, status: 'Próxima ao Vencimento' },
      { id: 'PARC-04', dueDate: '2026-07-01', value: 48000, status: 'Em aberto' }
    ]
  },
  {
    id: 'CONTR-2026-003',
    name: 'Microsoft 365 E5 Copilot',
    provider: 'Microsoft Brasil',
    category: 'SaaS',
    startDate: '2024-08-10',
    endDate: '2026-08-10',
    status: 'Próximo do Vencimento',
    monthlyValue: 24000,
    annualValue: 288000,
    currency: 'BRL',
    licensedSeats: 350,
    activeSeats: 342,
    excessLicenseCost: 220,
    sponsor: 'Carlos Magno (Diretor TI)',
    criticality: 'Crítica',
    contractLink: 'https://exemplo-infra.com/contracts/m365_enterprise_joint.pdf',
    sponsorEmail: 'carlos.magno@empresa.com.br',
    adminPanelLink: 'https://admin.microsoft.com',
    negotiationNotes: 'Contrato inclui licenças de Copilot de IA. Adoção média está em alta, mas há 8 licenças de colaboradores que saíram da empresa.',
    historicCosts: [
      { month: 'Jan', value: 24000 },
      { month: 'Fev', value: 24000 },
      { month: 'Mar', value: 24000 },
      { month: 'Abr', value: 24000 },
      { month: 'Mai', value: 24000 }
    ],
    projectionRenewal: 6,
    paymentFrequency: 'Mensal',
    paymentMethod: 'Faturamento',
    installments: [
      { id: 'PARC-01', dueDate: '2026-04-10', value: 24000, status: 'Paga' },
      { id: 'PARC-02', dueDate: '2026-05-10', value: 24000, status: 'Atrasada' },
      { id: 'PARC-03', dueDate: '2026-06-10', value: 24000, status: 'Em aberto' },
      { id: 'PARC-04', dueDate: '2026-07-10', value: 24000, status: 'Em aberto' }
    ]
  },
  {
    id: 'CONTR-2026-004',
    name: 'Slack Enterprise Grid',
    provider: 'Slack Technologies Inc.',
    category: 'SaaS',
    startDate: '2025-02-28',
    endDate: '2026-02-28',
    status: 'Expirado',
    monthlyValue: 8400,
    annualValue: 100800,
    currency: 'BRL',
    licensedSeats: 400,
    activeSeats: 210,
    excessLicenseCost: 45,
    sponsor: 'Mariana Luz (RH)',
    criticality: 'Média',
    contractLink: 'https://exemplo-infra.com/contracts/slack_grid_2025.pdf',
    sponsorEmail: 'mariana.luz@empresa.com.br',
    adminPanelLink: 'https://admin.slack.com',
    negotiationNotes: 'Contrato expirado. Operando atualmente em modelo prorrogado por faturamento direto. Urgência em migrar ociosidades ou unificar com MS Teams (já incluso na licença Microsoft E5) para economizar R$ 8.400 mensais.',
    historicCosts: [
      { month: 'Jan', value: 8400 },
      { month: 'Fev', value: 8400 },
      { month: 'Mar', value: 8400 },
      { month: 'Abr', value: 8400 },
      { month: 'Mai', value: 8400 }
    ],
    projectionRenewal: 12,
    paymentFrequency: 'Parcelado',
    installmentsCount: 12,
    paymentMethod: 'Faturamento',
    installments: [
      { id: 'PARC-01', dueDate: '2026-01-28', value: 8400, status: 'Paga' },
      { id: 'PARC-02', dueDate: '2026-02-28', value: 8400, status: 'Paga' },
      { id: 'PARC-03', dueDate: '2026-03-28', value: 8400, status: 'Atrasada' },
      { id: 'PARC-04', dueDate: '2026-04-28', value: 8400, status: 'Em aberto' }
    ]
  },
  {
    id: 'CONTR-2026-005',
    name: 'Suporte Técnico Hardware Dell',
    provider: 'Dell Technologies',
    category: 'Suporte',
    startDate: '2023-11-20',
    endDate: '2026-11-20',
    status: 'Ativo',
    monthlyValue: 6200,
    annualValue: 74400,
    currency: 'BRL',
    licensedSeats: 150,
    activeSeats: 150,
    excessLicenseCost: 80,
    sponsor: 'Eduardo Guedes (Infra)',
    criticality: 'Alta',
    contractLink: 'https://exemplo-infra.com/contracts/dell_support_carepro.pdf',
    sponsorEmail: 'eduardo.guedes@empresa.com.br',
    adminPanelLink: 'https://techdirect.dell.com',
    negotiationNotes: 'Renovação trienal realizada com êxito. Garante substituição de hardware em 4 horas (SLA Bronze). Monitorar inventário de ativos mensalmente.',
    historicCosts: [
      { month: 'Jan', value: 6200 },
      { month: 'Fev', value: 6200 },
      { month: 'Mar', value: 6200 },
      { month: 'Abr', value: 6200 },
      { month: 'Mai', value: 6200 }
    ],
    projectionRenewal: 4,
    paymentFrequency: 'Integral',
    paymentMethod: 'Faturamento',
    installments: [
      { id: 'PARC-01', dueDate: '2026-04-20', value: 6200, status: 'Paga' },
      { id: 'PARC-02', dueDate: '2026-05-20', value: 6200, status: 'Paga' },
      { id: 'PARC-03', dueDate: '2026-06-20', value: 6200, status: 'Em aberto' }
    ]
  },
  {
    id: 'CONTR-2026-006',
    name: 'Datadog Enterprise APM',
    provider: 'Datadog Europe',
    category: 'Infra',
    startDate: '2025-07-01',
    endDate: '2026-07-01',
    status: 'Próximo do Vencimento',
    monthlyValue: 16700,
    annualValue: 200400,
    currency: 'BRL',
    licensedSeats: 50,
    activeSeats: 32,
    excessLicenseCost: 380,
    sponsor: 'Tiago Mendes (CTO)',
    criticality: 'Alta',
    contractLink: 'https://exemplo-infra.com/contracts/datadog_signed_pro_2025.pdf',
    sponsorEmail: 'tiago.mendes@empresa.com.br',
    adminPanelLink: 'https://app.datadoghq.com',
    negotiationNotes: 'Custo de licenciamento de infraestrutura elevado. Estudar redução do consumo de logs não estruturados e limitar hosts de testes e Staging no Datadog.',
    historicCosts: [
      { month: 'Jan', value: 15200 },
      { month: 'Fev', value: 16100 },
      { month: 'Mar', value: 16500 },
      { month: 'Abr', value: 16700 },
      { month: 'Mai', value: 16700 }
    ],
    projectionRenewal: 10,
    paymentFrequency: 'Mensal',
    paymentMethod: 'Faturamento',
    installments: [
      { id: 'PARC-01', dueDate: '2026-04-01', value: 16700, status: 'Paga' },
      { id: 'PARC-02', dueDate: '2026-05-01', value: 16700, status: 'Paga' },
      { id: 'PARC-03', dueDate: '2026-06-01', value: 16700, status: 'Próxima ao Vencimento' },
      { id: 'PARC-04', dueDate: '2026-07-01', value: 16700, status: 'Em aberto' }
    ]
  },
  {
    id: 'CONTR-2026-007',
    name: 'OpenAI API (GPT-4o usage)',
    provider: 'OpenAI LLC',
    category: 'Assinatura de IA',
    startDate: '2025-10-01',
    endDate: '2026-10-01',
    status: 'Ativo',
    monthlyValue: 4500,
    annualValue: 54000,
    currency: 'BRL',
    licensedSeats: 150,
    activeSeats: 145,
    excessLicenseCost: 0,
    sponsor: 'Renan Oliveira (Lead AI)',
    criticality: 'Média',
    contractLink: 'https://openai.com/api-billing',
    sponsorEmail: 'renan.oliveira@empresa.com.br',
    adminPanelLink: 'https://platform.openai.com/admin',
    negotiationNotes: 'Pago via cartão de crédito corporativo para sustentar as APIs de chatbot e processamento de documentos internos.',
    historicCosts: [
      { month: 'Jan', value: 4200 },
      { month: 'Fev', value: 4800 },
      { month: 'Mar', value: 4300 },
      { month: 'Abr', value: 4500 },
      { month: 'Mai', value: 4500 }
    ],
    projectionRenewal: 15,
    paymentFrequency: 'Mensal',
    paymentMethod: 'Cartão de Crédito',
    cardHolder: 'Tiago Mendes (CTO)',
    installments: [
      { id: 'PARC-01', dueDate: '2026-04-01', value: 4500, status: 'Paga' },
      { id: 'PARC-02', dueDate: '2026-05-01', value: 4500, status: 'Paga' },
      { id: 'PARC-03', dueDate: '2026-06-01', value: 4500, status: 'Em aberto' }
    ]
  },
  {
    id: 'CONTR-2026-008',
    name: 'Anthropic Claude Enterprise',
    provider: 'Anthropic PBC',
    category: 'Assinatura de IA',
    startDate: '2025-11-15',
    endDate: '2026-11-15',
    status: 'Ativo',
    monthlyValue: 8000,
    extraMonthlySpent: 1850,
    annualValue: 96000,
    currency: 'BRL',
    licensedSeats: 80,
    activeSeats: 78,
    excessLicenseCost: 100,
    sponsor: 'Juliana Paiva (UX Lead)',
    criticality: 'Alta',
    contractLink: 'https://anthropic.com/enterprise-terms.pdf',
    sponsorEmail: 'juliana.paiva@empresa.com.br',
    adminPanelLink: 'https://console.anthropic.com',
    negotiationNotes: 'Cobrança direta e mensal de licenças corporativas do Claude Pro por cartão corporativo.',
    historicCosts: [
      { month: 'Jan', value: 8000 },
      { month: 'Fev', value: 8000 },
      { month: 'Mar', value: 8000 },
      { month: 'Abr', value: 8000 },
      { month: 'Mai', value: 9850 }
    ],
    projectionRenewal: 5,
    paymentFrequency: 'Mensal',
    paymentMethod: 'Cartão de Crédito',
    cardHolder: 'Eduardo Guedes (Finance Director)',
    installments: [
      { id: 'PARC-01', dueDate: '2026-04-15', value: 8000, status: 'Paga' },
      { id: 'PARC-02', dueDate: '2026-05-15', value: 9850, status: 'Paga' },
      { id: 'PARC-03', dueDate: '2026-06-15', value: 8000, status: 'Em aberto' }
    ]
  }
];
